substitutions:
  esphome_name: node10

esphome:
  name: ${esphome_name}

esp8266:
  board: esp01_1m

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
      hidden: true
  domain: !secret wifi_domain
  fast_connect: true
  reboot_timeout: 3min
  ap:
    ssid: "${esphome_name} Fallback Hotspot"
    password: !secret wifi_ap_password

uart:
  rx_pin: GPIO04
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      name: "${esphome_name} Ikea Vindriktning PM25"
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10
            
button:
  - platform: restart
    name: "${esphome_name} Restart"

captive_portal:

logger:

api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret ota_password
