substitutions:
  esphome_name: node08

esphome:
  name: ${esphome_name}
  platform: ESP32
  board: esp32dev

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
      hidden: true
  fast_connect: true
  reboot_timeout: 3min
  ap:
    ssid: "${esphome_name} Fallback Hotspot"
    password: !secret wifi_ap_password
    
esp32_ble_tracker:

bluetooth_proxy:

remote_receiver:
  pin: GPIO32
  dump: rc_switch
  tolerance: 50%
  filter: 250us
  idle: 4ms
  buffer_size: 2kb

button:
  - platform: restart
    name: "${esphome_name} Restart"

captive_portal:

logger:

api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret ota_password
